name: CI

on:
  push:
    branches:
      - main 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.103'

    - name: Add Github package repository
      run: |
        dotnet nuget add source --username FrancoMelandri --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/FrancoMelandri/index.json"

    - name: Build
      run: |
        dotnet build

    - name: Test
      run: |
        dotnet test --no-restore test/core/core-test.csproj /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Publish results
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{github.token}} 
        path-to-lcov: test/core/TestResults/coverage.info